### ISSUE TITLE
The dimension of cost

### ISSUE THREAD

**Issue by Zhong-eng** [LemonPi/pytorch_cem#1]
Hi there,

Thank you so much for your amazing work!

I'm now try to run your CEM on a Mujoco env. In the README, you said the dimension of cost is K x 1. 

I'm wondering whether it is a 2d array with the size (K, 1), or it is actually a 1d array of size (K,)

Thank you so much for your help!

**Comment by LemonPi** [comment]
It should be (K,), but I think it would also work with (K, 1) sized cost.
