### ISSUE TITLE
What is the running cost and where can I find it.

### ISSUE THREAD

**Issue by Zhong-eng** [LemonPi/pytorch_cem#2]
Hi there,

Thank you again for your amazing work!

I'm now trying to run the CEM on some mujoco env, such as Swimmer. But I'm not sure how to define a cost function for a mujoco env. Do you know how I should define it or where I can find some pre-defined cost function for a mujoco environment?

Thank you for your help!

**Comment by LemonPi** [comment]
The running cost is up to you to design, but a common one is a quadratic cost on the euclidean distance in state space (QR cost). For example, you have some goal state (or a set of goal states) x_goal, and your current state x_cur, then the Q part of the cost is `(x_goal - x_cur)^T Q (x_goal - x_cur)`, where Q is a positive definite matrix for weighting each dimension of the state in relation to how important it is to the goal (defines your distance function). The R part is a similar mechanism on the control (here the "goal" is often 0 control, meaning no control effort).

**Comment by Zhong-eng** [comment]
Thank you so much for your help! I'll think about it!

> The running cost is up to you to design, but a common one is a quadratic cost on the euclidean distance in state space (QR cost). For example, you have some goal state (or a set of goal states) x_goal, and your current state x_cur, then the Q part of the cost is `(x_goal - x_cur)^T Q (x_goal - x_cur)`, where Q is a positive definite matrix for weighting each dimension of the state in relation to how important it is to the goal (defines your distance function). The R part is a similar mechanism on the control (here the "goal" is often 0 control, meaning no control effort).
